import React from 'react'
import Head from 'next/head'
import styled from 'styled-components'
import { Nav } from '../components/Nav'
import { Aside } from '../components/Aside'
import { RecipeListWrapper } from '../components/RecipeListWrapper'
import { RecipeDetailModal } from '../components/RecipeDetailModal'
import { WelcomeModal } from '../components/WelcomeModal'
import { darken } from 'polished'
import { Logo } from '../components/Logo'

export default function Home(): JSX.Element {
	return (
		<>
			<Head>
				<title>Recipes</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<StyledPageBackground>
				<StyledPageGrid>
					<WelcomeModal />
					<Logo />
					<Nav />
					<Aside isMenu={false} />
					<StyledMain>
						<RecipeDetailModal />
						<RecipeListWrapper />
					</StyledMain>
					<FooterPlaceholder>
						Footer placeholder text
						{/* A React playground project from
						<a href='http://geordiemoore.com'>geordiemoore.com</a> */}
					</FooterPlaceholder>
				</StyledPageGrid>
			</StyledPageBackground>
		</>
	)
}

const StyledPageBackground = styled.div`
	background-color: ${p => darken(0.1, p.theme.color.gamma)};
`

const StyledPageGrid = styled.div`
	max-width: 1300px;
	margin: 0 auto;
	display: grid;
	grid-template-columns: repeat(12, 1fr);
	grid-template-rows: 5rem 6rem calc(100vh - 11rem);
	box-shadow: 0 0 15px 1px ${p => darken(0.2, p.theme.color.gamma)};
	@media only screen and (min-width: 576px) {
		grid-template-rows: 8rem calc(100vh - 10rem) 2rem;
	}
`

const StyledMain = styled.main`
	box-shadow: 0 0 10px 1px rgba(0, 0, 0, 0.1);
	overflow: hidden;
	grid-column: 1 / 13;
	@media only screen and (min-width: 576px) {
		grid-column: 6 / 13;
	}
	@media only screen and (min-width: 768px) {
		grid-column: 5 / 13;
	}
	@media only screen and (min-width: 992px) {
		grid-column: 4 / 13;
	}
`

const FooterPlaceholder = styled.div`
	background-color: ${p => p.theme.color.delta};
	grid-column: 1 / 13;
	display: flex;
	justify-content: center;
	align-items: center;
`
