import React from 'react'
import Head from 'next/head'
import styled from 'styled-components'
import { Nav } from '../components/Nav'
import { Aside } from '../components/Aside'
import { RecipeListWrapper } from '../components/RecipeListWrapper'
import { RecipeDetailModal } from '../components/RecipeDetailModal'
import { WelcomeModal } from '../components/WelcomeModal'

export default function Home(): JSX.Element {
	return (
		<>
			<Head>
				<title>Recipes</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<StyledPageBackground>
				<StyledPageGrid>
					<WelcomeModal />
					<Nav />
					<Aside />
					<StyledMain>
						<RecipeDetailModal />
						<RecipeListWrapper />
					</StyledMain>
				</StyledPageGrid>
			</StyledPageBackground>
		</>
	)
}

const StyledPageBackground = styled.div`
	background-color: ${p => p.theme.color.gamma};
`

const StyledPageGrid = styled.div`
	max-width: 1300px;
	margin: 0 auto;
	padding: 0 10px;
	display: grid;
	grid-template-columns: repeat(12, 1fr);
	grid-template-rows: 75px 50px minmax(calc(100vh - 125px), auto);
	//grid-template-rows: 75px 50px calc(100vh - 355px);
	@media only screen and (min-width: 576px) {
		//grid-template-rows: 100px minmax(calc(100vh - 100px), auto);
		grid-template-rows: 100px calc(100vh - 100px);
	}
`

const StyledMain = styled.main`
	grid-column: 1 / 13;
	@media only screen and (min-width: 576px) {
		grid-column: 4 / 13;
	}
	/* @media only screen and (min-width: 992px) {
		grid-column: 3 / 13;
	} */
`
