import Head from 'next/head'
import Link from 'next/link'
import React, { useEffect, useState } from 'react'
import styled from 'styled-components'

import { Nav } from '../components/Nav'
import { Searchbar } from '../components/Searchbar'
import { RecipeList } from '../components/RecipeList'
import { GetRecipesQuery, Recipe } from '../server/interfaces'
import { useGetRecipes } from '../hooks/useGetRecipes'
import { useDebounce } from '../hooks/useDebounce'

export default function Home() {
	const [recipeArray, setRecipeArray] = useState<Recipe[]>([])
	const [query, setQuery] = useState<GetRecipesQuery>()
	const { getRecipes } = useGetRecipes()
	const debouncedsearch = useDebounce(setQuery, 200)

	//const searchterms = {id:["91","92","93","94","95"]}
	const onSearch = (searchTerm:string) => {
		debouncedsearch({ name: searchTerm})
	}

	useEffect(() => {
		getRecipes(query).then(recipes => {
			setRecipeArray(recipes)
		})
	}, [query])

	return (
		<>
			<Head>
				<title>Recipes</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Main>
				<Nav>
					<Searchbar onSearch={onSearch} />
					<Button><Link href={`/newrecipe`}>New Recipe</Link></Button>
				</Nav>
				{recipeArray && <RecipeList recipesToRender={recipeArray} />}
			</Main>
		</>
	)
}

const Main = styled.main`
	min-height: 100vh;
	display: flex;
	flex-direction: column;
	align-items: center;
	background-color: ${p => p.theme.color.gamma};
`

const Button = styled.button`
	font: 700 2rem ${p => p.theme.font.title};
	line-height: 2rem;
	padding: .5rem 2rem;
	color: ${p => p.theme.color.delta};
	border: 2px solid ${p => p.theme.color.delta};
	background-color: ${p => p.theme.color.white};
	transition: .2s;
	&:hover {
		color: ${p => p.theme.color.white};
		background-color: ${p => p.theme.color.delta};
	}
`