import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import styled from 'styled-components'

import { Searchbar } from '../components/Searchbar'
import { RecipeList } from '../components/RecipeList'
import { GetRecipesQuery, Recipe } from '../server/interfaces'
import { useGetRecipes } from '../hooks/useGetRecipes'
import { useDebounce } from '../hooks/useDebounce'

export default function Home() {
	const [recipeArray, setRecipeArray] = useState<Recipe[]>([])
	const [query, setQuery] = useState<GetRecipesQuery>()
	const { getRecipes } = useGetRecipes()
	const debouncedsearch = useDebounce(setQuery, 200)
	//const searchterms = {id:["91","92","93","94","95"]}
	const onSearch = (searchTerm:string) => {
		debouncedsearch({ name: searchTerm})
	}

	useEffect(() => {
		getRecipes(query).then(recipes => {
			setRecipeArray(recipes)
		})
	}, [query])

	return (
		<>
			<Head>
				<title>Recipes</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Main>
				<Searchbar onSearch={onSearch} />
				{recipeArray && <RecipeList recipesToRender={recipeArray} />}
			</Main>
		</>
	)
}


const Main = styled.main`
	min-height: 100vh;
	padding: 3rem 0;
	flex: 1;
	display: flex;
	flex-direction: column;
	align-items: center;
	background-image: linear-gradient(
		to bottom right,
		rgba(140, 140, 180, 0.2),
		rgba(180, 140, 140, 0.5)
	);
`
