import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import { useEffect, useState } from 'react'
import styled from 'styled-components'

import { Searchbar } from '../components/Searchbar'
import { RecipeList } from '../components/RecipeList'
import { getRecipes } from '../server/functions'


const Main = styled.main`
  min-height: 100vh;
  padding: 3rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  background-image: linear-gradient(to bottom right, rgba(140,140,180,.2), rgba(180,140,140,.5));
`;

export default function Home() {
  const [recipeArray, setRecipeArray] = useState([])

  const SearchObj = {type: 'id', terms:["91","92","93","94","95"]}

  const fetchRecipes = async () => {
    const mongoResponse = await getRecipes(SearchObj)
    setRecipeArray(mongoResponse)
  }

  useEffect(() => {
    fetchRecipes()
  }, [])

  return (
    <>
      <Head>
        <title>Recipes</title>
        <meta name="description" content="Generated by create next app" />
     		<link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
      	<Searchbar />
        {recipeArray && <RecipeList recipesToRender={recipeArray}/>}
      </Main>

    </>
  )
}
